- name: add the kubernetes yum repo key
  yum_repository:
    name: kubernetes
    description: the kubernetes yum repo
    baseurl: "{{ kubernetes_yum_baseurl }}"
    gpgcheck: True
    gpgkey: "{{ kubernetes_yum_gpgkey }}"

- name: install the kubernetes yum packages
  yum:
    allow_downgrade: True
    name:
      - "kubectl-{{ kubernetes_full_version | kube_platform_version('redhat') }}"
      - "kubeadm-{{ kubernetes_full_version | kube_platform_version('redhat') }}"
  retries: 5
  delay: 5

- name: open etcd ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: True
  with_items:
  - "2379-2380/tcp"