---
- name: open bgp ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: True
  with_items:
  - "179/tcp"
  when: 
  - use_firewall 
  - ansible_os_family == "RedHat"

- name: Configure Network Manager
  template:
    src: etc/NetworkManager/conf.d/calico.conf
    dest: /etc/NetworkManager/conf.d/calico.conf
  when: ansible_os_family == "RedHat"

- name: pull manifest and apply any modifications
  run_once: False
  delegate_to: "{{ groups['k8s_controller_primary'][0] }}"
  modify_manifest:
    manifest_url: "{{ kubernetes_cni_calico_manifest_url }}"
    output_path: /tmp/calico.yml
    rules: "{{ kubernetes_cni_calico_manifest_mods }}"

- name: install CNI netowrking
  command: "/usr/bin/kubectl apply -f {{ item }}"
  run_once: True
  delegate_to: "{{ groups['k8s_controller_primary'][0] }}"
  with_items:
    - "{{ kubernetes_cni_calico_rbac_url }}"
    - /tmp/calico.yml
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"

- name: install calicoctl
  get_url:
     url: "{{ kubernetes_cni_calico_calicoctl_url }}"
     dest: /usr/bin/calicoctl
     mode: 0755
  retries: 10
  delay: 5
  when: kubernetes_cni_calico_install_calicoctl is defined and kubernetes_cni_calico_install_calicoctl|bool == True
