---
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: create docker directory
  file:
    dest: /etc/docker
    state: directory

- name: Configure additional engine options
  copy:
    content: "{{ docker_ce_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_ce_daemon_options is defined

- name: create a service.d directory for config
  file:
    dest: /etc/systemd/system/docker.service.d
    state: directory