---
- import_playbook: pre.yml

- name: basic config
  hosts: all
  become: yes
  roles: 
    - common
    - container_runtime

- name: kubernetes
  hosts: all
  become: yes
  roles:
    - kubernetes
