---
- import_playbook: pre.yml

- name: basic config
  hosts: all
  become: yes
  roles: 
    - common
    - container_runtime
    
- name: etcd
  hosts: etcd
  become: yes
  roles:
    - secure-etcd

- name: kubernetes
  hosts: all
  become: yes
  roles:
    - kubernetes

- name: create kubernetes control plane nodes
  hosts: k8s_controllers
  become: yes
  roles:
    - kubernetes-controlplane

- import_playbook: add_nodes.yml

- name: install CNI
  hosts: all
  become: yes
  roles:
    - kubernetes-cni
  tags:
    - kubernetes-cni
